name: portainer

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

x-restart: &default-restart
  restart: unless-stopped

services:
  portainer:
    image: portainer/portainer-ce:latest
    <<: *default-restart
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - traefik
      - portainer_agent
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(\"${PORTAINER_DOMAIN}\")"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=le"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    logging: *default-logging

  portainer_agent:
    image: portainer/agent:latest
    <<: *default-restart
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    logging: *default-logging

networks:
  traefik:
    name: traefik
    external: true
  portainer_agent:
    name: portainer_agent
    external: true

volumes:
  portainer_data:
    name: portainer_data
